name: Fetch Latest Commit

on:
  push:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  fetch_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Get latest commit
      run: |
        curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
        https://api.github.com/repos/Continuum3416/neumanncondition/commits | jq '.[0]' > latest_commit.json

    - name: Commit latest commit to repo
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add latest_commit.json
        git commit -m "Update latest commit info" || echo "No changes to commit"
        git push
